// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.1
// source: video_upload.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	VideoUploadService_UploadVideo_FullMethodName = "/videoupload.VideoUploadService/UploadVideo"
)

// VideoUploadServiceClient is the client API for VideoUploadService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VideoUploadServiceClient interface {
	UploadVideo(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[VideoChunk, UploadResponse], error)
}

type videoUploadServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVideoUploadServiceClient(cc grpc.ClientConnInterface) VideoUploadServiceClient {
	return &videoUploadServiceClient{cc}
}

func (c *videoUploadServiceClient) UploadVideo(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[VideoChunk, UploadResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &VideoUploadService_ServiceDesc.Streams[0], VideoUploadService_UploadVideo_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[VideoChunk, UploadResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type VideoUploadService_UploadVideoClient = grpc.ClientStreamingClient[VideoChunk, UploadResponse]

// VideoUploadServiceServer is the server API for VideoUploadService service.
// All implementations must embed UnimplementedVideoUploadServiceServer
// for forward compatibility.
type VideoUploadServiceServer interface {
	UploadVideo(grpc.ClientStreamingServer[VideoChunk, UploadResponse]) error
	mustEmbedUnimplementedVideoUploadServiceServer()
}

// UnimplementedVideoUploadServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVideoUploadServiceServer struct{}

func (UnimplementedVideoUploadServiceServer) UploadVideo(grpc.ClientStreamingServer[VideoChunk, UploadResponse]) error {
	return status.Errorf(codes.Unimplemented, "method UploadVideo not implemented")
}
func (UnimplementedVideoUploadServiceServer) mustEmbedUnimplementedVideoUploadServiceServer() {}
func (UnimplementedVideoUploadServiceServer) testEmbeddedByValue()                            {}

// UnsafeVideoUploadServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VideoUploadServiceServer will
// result in compilation errors.
type UnsafeVideoUploadServiceServer interface {
	mustEmbedUnimplementedVideoUploadServiceServer()
}

func RegisterVideoUploadServiceServer(s grpc.ServiceRegistrar, srv VideoUploadServiceServer) {
	// If the following call pancis, it indicates UnimplementedVideoUploadServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VideoUploadService_ServiceDesc, srv)
}

func _VideoUploadService_UploadVideo_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(VideoUploadServiceServer).UploadVideo(&grpc.GenericServerStream[VideoChunk, UploadResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type VideoUploadService_UploadVideoServer = grpc.ClientStreamingServer[VideoChunk, UploadResponse]

// VideoUploadService_ServiceDesc is the grpc.ServiceDesc for VideoUploadService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VideoUploadService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "videoupload.VideoUploadService",
	HandlerType: (*VideoUploadServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "UploadVideo",
			Handler:       _VideoUploadService_UploadVideo_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "video_upload.proto",
}
